import {
  AscendexStrategy,
  BidgetStrategy,
  BigOneStrategy,
  BinanceStrategy,
  BingxStrategy,
  BitcoinTradeStrategy,
  BitfinexStrategy,
  BitflyerStrategy,
  BitforexStrategy,
  BithumpStrategy,
  BitkubStrategy,
  BitpandaStrategy,
  BitrueStrategy,
  BitsoStrategy,
  BitstampStrategy,
  BkexStrategy,
  BlockchainStrategy,
  BrasilBitcoinStrategy,
  BtcexStrategy,
  ByBitStrategy,
  CexStrategy,
  ChilizStrategy,
  CoinBaseStrategy,
  CoincheckStrategy,
  CoinextStrategy,
  CoinsbitStrategy,
  CointrStrategy,
  CoinwStrategy,
  CryptoComStrategy,
  CryptologyStrategy,
  DextradeStrategy,
  DigifinexStrategy,
  DYDYXStrategy,
  ExmarketsStrategy,
  FoxBitStrategy,
  GateIoTradeStrategy,
  GeminiStategy,
  HitBTCStrategy,
  HuobiStrategy,
  KrakenStrategy,
  KuCoinStratefy,
  LatokenStrategy,
  LbkexStrategy,
  MercadoBitcoinStrategy,
  MexcStrategy,
  NovaDAXStrategy,
  OkxStrategy,
  P2PB2BStrategy,
  PhemexStrategy,
  PionexStrategy,
  PolonieskStrategy,
  ProbitStrategy,
  RipioTradeStrategy,
  TokoCryptoStrategy,
  WhitebitStrategy,
  WooStrategy,
  XTStrategy,
  ZtbStrategy,
} from "../modules/exchanges/Exchanges";
import { ExchangeStrategy } from "../modules/exchanges/ExchangeStrategy";

const exchangeStrategies: ExchangeStrategy[] = [
  new BinanceStrategy(),
  new BitsoStrategy(),
  new BrasilBitcoinStrategy(),
  new CoinBaseStrategy(),
  new ChilizStrategy(),
  new CoinextStrategy(),
  new CryptoComStrategy(),
  new FoxBitStrategy(),
  new CexStrategy(),
  new GeminiStategy(),
  new BithumpStrategy(),
  new ProbitStrategy(),
  new P2PB2BStrategy(),
  new HuobiStrategy(),
  new KrakenStrategy(),
  new KuCoinStratefy(),
  new NovaDAXStrategy(),
  new MexcStrategy(),
  new MercadoBitcoinStrategy(),
  new HitBTCStrategy(),
  new BitfinexStrategy(),
  new DigifinexStrategy(),
  new ByBitStrategy(),
  new CoinwStrategy(),
  new PolonieskStrategy(),
  new BitstampStrategy(),
  new XTStrategy(),
  new BidgetStrategy(),
  new PhemexStrategy(),
  new OkxStrategy(),
  new CoincheckStrategy(),
  new BitcoinTradeStrategy(),
  new AscendexStrategy(),
  new LbkexStrategy(),
  new BkexStrategy(),
  new CoinsbitStrategy(),
  new BitrueStrategy(),
  new BtcexStrategy(),
  new GateIoTradeStrategy(),
  new BingxStrategy(),
  new BigOneStrategy(),
  new WhitebitStrategy(),
  new BitkubStrategy(),
  new DextradeStrategy(),
  new PionexStrategy(),
  new BitforexStrategy(),
  new CryptologyStrategy(),
  new WooStrategy(),
  new LatokenStrategy(),
  new BlockchainStrategy(),
  new BitpandaStrategy(),
  new CointrStrategy(),
  new ExmarketsStrategy(),
  new ZtbStrategy(),
  new BitflyerStrategy(),
  new DYDYXStrategy(),
  new RipioTradeStrategy(),
  new TokoCryptoStrategy(),
];

// export const tickerRouter = createRouter().query("getAll", {
//   async resolve({ ctx }) {
//     const promisesArray = exchangeStrategies.map(async (exchangeStrategy) => {
//       const coinPair = exchangeStrategy.formatPair("btc", "usdt");

//       return exchangeStrategy.fetchOrderbook(coinPair).then((exchangeData) => {
//         return exchangeData;
//       });
//     });

//     const results = await Promise.allSettled(promisesArray);
//     return results;
//   },
// });
